=== wbyoussef/XHDL_studio/IDE/src/dtd.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by WALID (N/A) -->
<!--I P -->
<!ELEMENT IP (documentation, version, entity, package, list_arch, project_man)>
<!ELEMENT documentation (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT project_man (#PCDATA)>
<!--project management-->
<!--Entity -->
<!ELEMENT entity (list_params?, list_bus)>
<!ATTLIST entity
	name NMTOKEN #REQUIRED
>
<!--Package-->
<!ELEMENT package (list_bus)>
<!ATTLIST package
	name NMTOKEN #REQUIRED
>
<!--List of Bus-->
<!ELEMENT list_params (param)*>
<!ELEMENT list_bus (signal)*>
<!ELEMENT param (#PCDATA)>
<!--Signal-->
<!ELEMENT signal (stype?, direction?, high_val?, low_val?, is_bit?, is_reset?, is_clock?, initial_val?, is_flipflop?, reset?, clock?, reference?, comment?)>
<!ATTLIST signal
	name NMTOKEN #REQUIRED
>
<!ELEMENT stype (#PCDATA)>
<!-- used for enumerated type or predifined type -->
<!ELEMENT direction (#PCDATA)>
<!ELEMENT high_val (#PCDATA)>
<!ELEMENT low_val (#PCDATA)>
<!ELEMENT initial_val (#PCDATA)>
<!ELEMENT is_bit (#PCDATA)>
<!ELEMENT is_reset (#PCDATA)>
<!ELEMENT is_clock (#PCDATA)>
<!ELEMENT is_flipflop (#PCDATA)>
<!ELEMENT reset (#PCDATA)>
<!-- for flipflop signal-->
<!ELEMENT clock (#PCDATA)>
<!-- for flipflop signal -->
<!ELEMENT reference (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!--commentaire identique pour les autres elements-->
<!--List of architectures -->
<!ELEMENT list_arch (arch)*>
<!--Architecture-->
<!ELEMENT arch (type, list_enumtype?, list_bus?, body)>
<!--entity de reference pour l'architecture-->
<!ELEMENT type (#PCDATA)>
<!ATTLIST arch
	name NMTOKEN #REQUIRED
>
<!--list of enumerated types -->
<!ELEMENT list_enumtype (enumtype)*>
<!--Enumerate type-->
<!ELEMENT enumtype (enumlist)>
<!ELEMENT enumlist (id+)>
<!ELEMENT id (#PCDATA)>
<!ATTLIST enumtype
	name NMTOKEN #REQUIRED
>
<!--Body of Architecture-->
<!ELEMENT body (list_maps?, list_stat?, list_process?, list_plain?)>
<!--List of Static-->
<!ELEMENT list_stat (static)*>
<!--Static assignement-->
<!ELEMENT static (affect | if_gen | for_gen)>
<!-- TODO : define : for_gen  -->
<!--affectation instruction-->
<!ELEMENT affect (output, input*, default_expr, cond_expr*, comment?)>
<!ELEMENT default_expr (expr)>
<!ELEMENT output (#PCDATA)>
<!ELEMENT input (#PCDATA)>
<!--Expression-->
<!ELEMENT expr (sig_name | number | litteral | (op, expr) | (expr, op, expr))>
<!ELEMENT cond (sig_name | number | litteral | (op, expr) | (expr, op, expr))>
<!ELEMENT cond_expr (expr, cond)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT litteral (#PCDATA)>
<!ELEMENT op (#PCDATA)>
<!--list of process-->
<!ELEMENT list_process (process)*>
<!--Process-->
<!ELEMENT process (comment?, label, sens_list, declarations?, list_intsructions)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT sens_list (sig_name)*>
<!ELEMENT sig_name (#PCDATA)>
<!ELEMENT declarations (signal)*>
<!--list of instructions-->
<!ELEMENT list_intsructions (instruction)*>
<!ELEMENT instruction ((sig_name, simple_instruction) | conditional_inst)>
<!ELEMENT simple_instruction ((simple_instruction, op, simple_instruction) | null | number | sig_name)>
<!ELEMENT null (#PCDATA)>
<!ELEMENT conditional_inst (condition, true_inst?, false_inst?)>
<!ELEMENT true_inst (instruction)*>
<!ELEMENT false_inst (instruction)*>
<!ELEMENT condition (expr)>
<!--sequential statement -->
<!ELEMENT sequential (affect | if | case | for)>
<!--IF instruction-->
<!ELEMENT if ((cond, list_sequential)+, else?)>
<!ELEMENT else (list_sequential)>
<!--CASE instruction-->
<!ELEMENT case (expr, (value, list_sequential)+, default?)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT default (list_sequential)>
<!--For  instruction-->
<!ELEMENT for (param_name, range, list_sequential)>
<!ELEMENT param_name (#PCDATA)>
<!ELEMENT range (((low_val, high_val)) | litteral)>
<!ATTLIST range
	startfrom (high | low) "low"
>
<!--list of plain-->
<!ELEMENT list_plain (plain)*>
<!--plain text -->
<!ELEMENT plain (langage, text)>
<!ELEMENT langage (#PCDATA)>
<!ELEMENT text (#PCDATA)>
<!-- NB: all simple type are regroupped with there ancestors-->
<!-- List of port mapping -->
<!ELEMENT list_maps (port_map)*>
<!-- List of port mapping -->
<!ELEMENT port_map (label, component_name, list_connect)>
<!--label already defined-->
<!ELEMENT component_name (#PCDATA)>
<!ELEMENT list_connect (connect)+>
<!--list of connection -->
<!ELEMENT connect (formal, actual)>
<!--connection between formal signal of the componant and the actuan signal-->
<!ELEMENT formal (#PCDATA)>
<!ELEMENT actual (#PCDATA)>

=== wbyoussef/XHDL_studio/IDE/examples/yyy.xml
<!DOCTYPE IP SYSTEM "dtd.dtd">
<IP>
<documentation></documentation>

<version></version>

<entity name="default_ip_name">
<list_params></list_params><list_bus><signal name="A">
<direction>IN</direction>
<high_val>0</high_val>
<low_val>0</low_val>
<is_bit>TRUE</is_bit>
<is_reset>FALSE</is_reset>
<is_clock>FALSE</is_clock>
<initial_val></initial_val>
<is_flipflop>FALSE</is_flipflop>
<reference></reference>
<comment></comment>
</signal>
<signal name="B">
<direction>IN</direction>
<high_val>0</high_val>
<low_val>0</low_val>
<is_bit>TRUE</is_bit>
<is_reset>FALSE</is_reset>
<is_clock>FALSE</is_clock>
<initial_val></initial_val>
<is_flipflop>FALSE</is_flipflop>
<reference></reference>
<comment></comment>
</signal>
<signal name="C">
<direction>OUT</direction>
<high_val>0</high_val>
<low_val>0</low_val>
<is_bit>TRUE</is_bit>
<is_reset>FALSE</is_reset>
<is_clock>FALSE</is_clock>
<initial_val></initial_val>
<is_flipflop>FALSE</is_flipflop>
<reference></reference>
<comment></comment>
</signal>
</list_bus>
</entity>


<package name="default_ip_name">
<list_bus></list_bus>
</package>

<list_arch>
<arch name="rtl">
<type>N/A</type>
<list_enumtype></list_enumtype>
<list_bus></list_bus>
<body>


<list_maps></list_maps>

<list_stat></list_stat>

<list_process><process>
<comment>  </comment>
<label>process1</label>
<sens_list><sig_name>A</sig_name>
<sig_name>B</sig_name>
</sens_list>
<list_intsructions><instruction>
<sig_name>C</sig_name>
<simple_instruction>
<simple_instruction>
<sig_name>A</sig_name>
</simple_instruction>
<op>OR</op>
<simple_instruction>
<sig_name>B</sig_name>
</simple_instruction>
</simple_instruction>
</instruction>
</list_intsructions>
</process>
</list_process>

<list_plain></list_plain>


</body>
</arch>
</list_arch>
<project_man></project_man>
</IP>

=== wbyoussef/XHDL_studio/IDE/examples/size_converter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE IP SYSTEM "dtd.dtd">
<IP>
  <documentation/>
  <version/>
  <entity name="CPU_size_converter">
    <list_params>
      <param>enable_retiming</param>
      <param>fifo_size</param>
    </list_params>
    <list_bus>
      <signal name="In1">
        <direction>IN</direction>
        <high_val>0</high_val>
        <low_val>0</low_val>
        <is_bit>TRUE</is_bit>
        <is_reset>FALSE</is_reset>
        <is_clock>FALSE</is_clock>
        <initial_val/>
        <is_flipflop>FALSE</is_flipflop>
        <reference/>
        <comment>N/A</comment>
      </signal>
      <signal name="Out1">
        <direction>OUT</direction>
        <high_val>0</high_val>
        <low_val>0</low_val>
        <is_bit>TRUE</is_bit>
        <is_reset>FALSE</is_reset>
        <is_clock>FALSE</is_clock>
        <initial_val/>
        <is_flipflop>FALSE</is_flipflop>
        <reference/>
        <comment>N/A</comment>
      </signal>
      <signal name="Out2">
        <direction>OUT</direction>
        <high_val>0</high_val>
        <low_val>0</low_val>
        <is_bit>TRUE</is_bit>
        <is_reset>FALSE</is_reset>
        <is_clock>FALSE</is_clock>
        <initial_val/>
        <is_flipflop>FALSE</is_flipflop>
        <reference/>
        <comment>N/A</comment>
      </signal>
      <signal name="In2">
        <direction>IN</direction>
        <high_val>0</high_val>
        <low_val>0</low_val>
        <is_bit>TRUE</is_bit>
        <is_reset>FALSE</is_reset>
        <is_clock>FALSE</is_clock>
        <initial_val/>
        <is_flipflop>FALSE</is_flipflop>
        <reference/>
        <comment>N/A</comment>
      </signal>
      <signal name="CPU_req">
        <direction>IN</direction>
        <high_val>0</high_val>
        <low_val>0</low_val>
        <is_bit>TRUE</is_bit>
        <is_reset>FALSE</is_reset>
        <is_clock>FALSE</is_clock>
        <initial_val/>
        <is_flipflop>FALSE</is_flipflop>
        <reference/>
        <comment>N/A</comment>
      </signal>
      <signal name="CPU_ack">
        <direction>OUT</direction>
        <high_val>0</high_val>
        <low_val>0</low_val>
        <is_bit>TRUE</is_bit>
        <is_reset>FALSE</is_reset>
        <is_clock>FALSE</is_clock>
        <initial_val/>
        <is_flipflop>FALSE</is_flipflop>
        <reference/>
        <comment>N/A</comment>
      </signal>
      <signal name="CPU_data">
        <direction>IN</direction>
        <high_val>0</high_val>
        <low_val>63</low_val>
        <is_bit>FALSE</is_bit>
        <is_reset>FALSE</is_reset>
        <is_clock>FALSE</is_clock>
        <initial_val/>
        <is_flipflop>FALSE</is_flipflop>
        <reference/>
        <comment>N/A</comment>
      </signal>
      <signal name="CPU_addr">
        <direction>IN</direction>
        <high_val>0</high_val>
        <low_val>63</low_val>
        <is_bit>FALSE</is_bit>
        <is_reset>FALSE</is_reset>
        <is_clock>FALSE</is_clock>
        <initial_val/>
        <is_flipflop>FALSE</is_flipflop>
        <reference/>
        <comment>N/A</comment>
      </signal>
      <signal name="CPU_be">
        <direction>IN</direction>
        <high_val>0</high_val>
        <low_val>7</low_val>
        <is_bit>FALSE</is_bit>
        <is_reset>FALSE</is_reset>
        <is_clock>FALSE</is_clock>
        <initial_val/>
        <is_flipflop>FALSE</is_flipflop>
        <reference/>
        <comment>N/A</comment>
      </signal>

      <signal name="BUS_req">
        <direction>OUT</direction>
        <high_val>0</high_val>
        <low_val>0</low_val>
        <is_bit>TRUE</is_bit>
        <is_reset>FALSE</is_reset>
        <is_clock>FALSE</is_clock>
        <initial_val/>
        <is_flipflop>FALSE</is_flipflop>
        <reference/>
        <comment>N/A</comment>
      </signal>
      <signal name="BUS_ack">
        <direction>IN</direction>
        <high_val>0</high_val>
        <low_val>0</low_val>
        <is_bit>TRUE</is_bit>
        <is_reset>FALSE</is_reset>
        <is_clock>FALSE</is_clock>
        <initial_val/>
        <is_flipflop>FALSE</is_flipflop>
        <reference/>
        <comment>N/A</comment>
      </signal>
      <signal name="BUS_data">
        <direction>OUT</direction>
        <high_val>0</high_val>
        <low_val>63</low_val>
        <is_bit>FALSE</is_bit>
        <is_reset>FALSE</is_reset>
        <is_clock>FALSE</is_clock>
        <initial_val/>
        <is_flipflop>FALSE</is_flipflop>
        <reference/>
        <comment>N/A</comment>
      </signal>
      <signal name="BUS_addr">
        <direction>OUT</direction>
        <high_val>0</high_val>
        <low_val>63</low_val>
        <is_bit>FALSE</is_bit>
        <is_reset>FALSE</is_reset>
        <is_clock>FALSE</is_clock>
        <initial_val/>
        <is_flipflop>FALSE</is_flipflop>
        <reference/>
        <comment>N/A</comment>
      </signal>
      <signal name="BUS_be">
        <direction>OUT</direction>
        <high_val>0</high_val>
        <low_val>7</low_val>
        <is_bit>FALSE</is_bit>
        <is_reset>FALSE</is_reset>
        <is_clock>FALSE</is_clock>
        <initial_val/>
        <is_flipflop>FALSE</is_flipflop>
        <reference/>
        <comment>N/A</comment>
      </signal>

      <signal name="MyClock">
        <direction>IN</direction>
        <high_val>0</high_val>
        <low_val>0</low_val>
        <is_bit>TRUE</is_bit>
        <is_reset>FALSE</is_reset>
        <is_clock>TRUE</is_clock>
        <initial_val/>
        <is_flipflop>FALSE</is_flipflop>
        <reference/>
        <comment>N/A</comment>
      </signal>
    </list_bus>
  </entity>
  <package name="default_ip_name">
    <list_bus/>
  </package>
  <list_arch>
    <arch name="rtl">
      <type/>
      <list_enumtype/>
      <list_bus/>
      <body>
        <list_maps/>
        <list_stat/>
        <list_process/>
        <list_plain/>
      </body>
    </arch>
  </list_arch>
  <project_man/>
</IP>

=== wbyoussef/XHDL_studio/IDE/examples/xxx.xml
<!DOCTYPE IP SYSTEM "dtd.dtd">
<IP>
<documentation></documentation>

<version></version>

<entity name="default_ip_name">
<list_params><param>param1</param>
<param>param2</param>
<param>param3</param>
<param>param4</param>
</list_params><list_bus><signal name="ddd">
<direction>IN</direction>
<high_val>0</high_val>
<low_val>0</low_val>
<is_bit>TRUE</is_bit>
<is_reset>FALSE</is_reset>
<is_clock>FALSE</is_clock>
<initial_val></initial_val>
<is_flipflop>FALSE</is_flipflop>
<reference></reference>
<comment>N/A</comment>
</signal>
</list_bus>
</entity>


<package name="default_ip_name">
<list_bus></list_bus>
</package>

<list_arch>
<arch name="rtl">
<type></type>
<list_enumtype></list_enumtype>
<list_bus></list_bus>
<body>


<list_maps></list_maps>

<list_stat></list_stat>

<list_process></list_process>

<list_plain></list_plain>


</body>
</arch>
</list_arch>
<project_man></project_man>
</IP>

=== wbyoussef/XHDL_studio/IDE/src/default_ip.xml
<!DOCTYPE IP SYSTEM "dtd.dtd">
<IP>
<documentation></documentation>

<version></version>

<entity name="default_ip_nameXXX">
<list_params></list_params><list_bus><signal name="a">
<direction>IN</direction>
<high_val>0</high_val>
<low_val>0</low_val>
<is_bit>TRUE</is_bit>
<is_reset>FALSE</is_reset>
<is_clock>FALSE</is_clock>
<initial_val></initial_val>
<is_flipflop>FALSE</is_flipflop>
<reference></reference>
<comment>N/A</comment>
</signal>
<signal name="b">
<direction>IN</direction>
<high_val>0</high_val>
<low_val>0</low_val>
<is_bit>TRUE</is_bit>
<is_reset>FALSE</is_reset>
<is_clock>FALSE</is_clock>
<initial_val></initial_val>
<is_flipflop>FALSE</is_flipflop>
<reference></reference>
<comment>N/A</comment>
</signal>
<signal name="c">
<direction>OUT</direction>
<high_val>0</high_val>
<low_val>0</low_val>
<is_bit>TRUE</is_bit>
<is_reset>FALSE</is_reset>
<is_clock>FALSE</is_clock>
<initial_val></initial_val>
<is_flipflop>FALSE</is_flipflop>
<reference></reference>
<comment>N/A</comment>
</signal>
<signal name="d">
<direction>OUT</direction>
<high_val>0</high_val>
<low_val>0</low_val>
<is_bit>TRUE</is_bit>
<is_reset>FALSE</is_reset>
<is_clock>FALSE</is_clock>
<initial_val></initial_val>
<is_flipflop>FALSE</is_flipflop>
<reference></reference>
<comment>N/A</comment>
</signal>
</list_bus>
</entity>


<package name="default_ip_name">
<list_bus></list_bus>
</package>

<list_arch>
<arch name="rtl">
<type>N/A</type>
<list_enumtype></list_enumtype>
<list_bus></list_bus>
<body>


<list_maps></list_maps>

<list_stat></list_stat>

<list_process><process>
<comment>         </comment>
<label>new_process0</label>
<sens_list><sig_name>a</sig_name>
<sig_name>b</sig_name>
</sens_list>
<list_intsructions><instruction>
<sig_name>c</sig_name>
<simple_instruction>
<simple_instruction>
<sig_name>a</sig_name>
</simple_instruction>
<op>AND</op>
<simple_instruction>
<sig_name>b</sig_name>
</simple_instruction>
</simple_instruction>
</instruction>
</list_intsructions>
</process>
<process>
<comment>    </comment>
<label>process_d</label>
<sens_list><sig_name>a</sig_name>
<sig_name>b</sig_name>
</sens_list>
<list_intsructions><instruction>
<sig_name>d</sig_name>
<simple_instruction>
<simple_instruction>
<sig_name>a</sig_name>
</simple_instruction>
<op>OR</op>
<simple_instruction>
<sig_name>b</sig_name>
</simple_instruction>
</simple_instruction>
</instruction>
</list_intsructions>
</process>
</list_process>

<list_plain></list_plain>


</body>
</arch>
</list_arch>
<project_man></project_man>
</IP>
